# Generated by Django 5.0.2 on 2024-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('city', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer'), ('Project Manager', 'Project Manager')], max_length=255)),
            ],
        ),
    ]
