# Generated by Django 5.0.2 on 2024-02-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Register'},
        ),
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
