# Generated by Django 5.0.2 on 2024-02-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_alter_register_options_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Register', 'verbose_name_plural': 'Register'},
        ),
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dob',
        ),
    ]
