# Generated by Django 5.0.2 on 2024-02-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_register_options_remove_register_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='city',
        ),
    ]
