# Generated by Django 5.0.2 on 2024-02-16 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_remove_register_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 10, 48, 47, 480004)),
        ),
        migrations.AlterField(
            model_name='register',
            name='designation',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Senior Developer', 'Senior Developer'), ('Project Manager', 'Project Manager')], max_length=255),
        ),
    ]
